name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["CI Test Backend"]
    types:
      - completed

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}  # Ensure it only runs on main and after successful tests
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build and push the backend image
      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops:backend
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build and push the database image
      - name: Build and push database image
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops:database
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build and push the HTTP server image
      - name: Build and push HTTP server image
        uses: docker/build-push-action@v3
        with:
          context: ./http-server
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops:httpd
          push: ${{ github.ref == 'refs/heads/main' }}
